version: '3'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./log:/var/log/nginx
      - ./www/index.html:/usr/share/nginx/html/index.html
    container_name: webserver
    